### ISSUE TITLE
Horizontal rule shortcut and a number of buttons non-functional on Mac Anki 2.0.41

### ISSUE THREAD

**Issue by GitHubScreenName** [Neftas/supplementary-buttons-anki#100]
Hi there - thanks again for your hard work on a wonderful app.
Using a Mac (OSX Yosemite), Anki 2.0.41. Many of the cards are "Type Answer" type.

•Horizontal rule shortcut (Command+Shift+Alt+_) (also tried Ctrl+H as listed on github page) does nothing, can only use by clicking on icon.

Some additional issues:
•Code, Blockquotes, Keyboard, Create a code block & Add a background color do not do anything on my Anki, as above. Clicking on the button or using shortcut generates no response.

2 general questions:
•Will the formatting made with the add-on - specifically, the roll-over abbreviations - show up if imported to Anki which does not have the add-on installed? How about on mobile iOs app?
•Can shortcuts be modified? Even if the header button would work, underscore cannot be used in this conjunction on OSX, as it is hard-mapped to produce a 1/2 symbol.

Thank you very much in advance if you have a chance to reply or address any of these issues.

**Comment by Neftas** [comment]
Please read the documentation, most of your questions are answered there. Also, you haven't responded to my reply to your previous question in #98, where you asked some of the same questions. If anything is unclear after that, feel free to ask again.
