### ISSUE TITLE
Table stylesheet makes whole card a table?

### ISSUE THREAD

**Issue by MrTre** [Neftas/supplementary-buttons-anki#101]
Hey guys,

sorry to bother you with something like this, but I'm not really a programmer. I tried to use CSS to style my tables just like you suggest, but I end up turning the whole card into an td cell. How does that come and how can I fix that?

`.card {
 font-family: Arial;
 font-size: 15px;
 text-align: left;
 color: black;
 background-color: white;
 overflow:visible;
}

td {
 padding: 0px;
 max-width:1600px;
}

table {border-collapse:collapse;border-spacing:0;border-color:#ccc;}

table td{font-family:Arial, sans-serif;font-size:14px;padding:10px 4px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#fff;}

table th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 4px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:#ccc;color:#333;background-color:#f0f0f0;}

table table-ecrz{font-size:14px;vertical-align:top}

table table-yw4l{vertical-align:top}

table table-b7b8{background-color:#f9f9f9;vertical-align:top}

.ausklappen {
 font-weight: normal;
 font-style: normal;
//text-decoration: none;
}

.zusatzinfo {
 font-size: 12px;
 max-width: 500px;
}

.mobile .card { padding: 5px; }

.UeberAnzeigen {
    cursor: pointer;
    width:0px;
    height:0px;
    border-top:30px solid transparent;
    border-left: 30px solid transparent;
    border-right: 0px solid transparent;
}.UeberAnzeigen:hover {
    border-top:30px solid #DFDFDF;
}.UeberAnzeigen:active {
    border-top:30px solid grey;
}
.UeberAusblenden {
    cursor: pointer;
    width:0px;
    height:0px;
    border-top:30px solid #DFDFDF;
    border-left: 30px solid transparent;
    border-right: 0px solid transparent;
}
.UeberAusblenden:hover {
    border-top:30px solid #BEBEBE;
}
.UeberAusblenden:active {
    border-top:30px solid grey;
}
.cloze {
 font-weight: bold;
 color: #DF0101;
}`

![screenshot 2017-04-11 12 38 55](https://cloud.githubusercontent.com/assets/27279993/24905337/ec75ee44-1eb3-11e7-8806-616eda90775f.png)

![screenshot 2017-04-11 12 35 02](https://cloud.githubusercontent.com/assets/27279993/24905214/796f0ea8-1eb3-11e7-902b-b54a7f912541.png)

**Comment by Neftas** [comment]
Hi @MrTre, you wrote a awful lot of CSS for someone who doesn't know what he's doing ;) However, this might not be the best place for you to ask such questions, since this is not actually a problem with the add-on. Also, my CSS skills are not that great :) You might be able to find help somewhere else, for example on StackOverflow, or ask just about anybody who is into front-end development. Good luck!
