### ISSUE TITLE
Anki 2.1 compatability

### ISSUE THREAD

**Issue by munyari** [Neftas/supplementary-buttons-anki#102]
This addon does not seem to be compatible with anki's updated plugin interface in versions >= 2.1.0

**Comment by Neftas** [comment]
Hi @munyari, you are right. This issue has previously been pointed out in #96. The Anki 2.1.x branch is currently in the alpha stage, so support is currently not provided. In fact, you'll find that most add-ons for 
Anki won't work with 2.1.x. Eventually, when Anki 2.1 becomes stable, I will update this add-on and make it compatible. As far as I can tell, it involves mostly upgrading to Python 3.

**Comment by munyari** [comment]
Thanks for the response @Neftas. Closing in favor of #96
