### ISSUE TITLE
Add the language name as a class to the main div

### ISSUE THREAD

**Issue by rcoelho** [Neftas/supplementary-buttons-anki#103]
Hi Stefan, thanks for Power Format Pack, it is awesome!

I'm using code highlighting and I'd like to style XML and Java attributes in different colors.
However, both use the class "na" (Name.Attribute) and there's no other way to differentiate them.

Would it be viable to get the language name, when defined, and add them as a class to the `<div class="codehilite">`, resulting in `<div class="codehilite java">`, for example?

Thanks!

**Comment by Neftas** [comment]
@rcoelho I use `pygments` for the code generation. Although I think I can do what you want, it would probably involve me editing the `pygments` source code, or possibly writing a messy JavaScript solution without touching `pygments`, neither of which sound very appealing to me. I would suggest you turn this into a feature request for upstream.

**Comment by rcoelho** [comment]
That makes sense. Thanks!
