### ISSUE TITLE
How to delete the border of the <span>?

### ISSUE THREAD

**Issue by Juddd** [Neftas/supplementary-buttons-anki#106]
If I use your *Markdown* to create a code block like
```
insert into 表1 (字段1,字段2) select 字段a,字段b
from 表2 [where condition];
```
I will get a result like
![](http://i.stack.imgur.com/NXEk1.png)

as the *HTML*,every Chinese character have a border like

 <span style="color: #a40000; border: 1px solid #ef2929">表</span>

How to delete those `border`？

**Comment by Neftas** [comment]
@Juddd This is a known issue with Pygments, the Python library I'm using for syntax highlighting. Characters outside the ASCII range are considered errors by the parser, and get a red square around them. You can either changes your cards and include only ASCII in them, or open a bug report with the developers from Pygments.

**Comment by Juddd** [comment]
@Neftas Sorry for distub again, though this problem derive form the Pygments(as you see).I think there are some workaroun by your python code.You can change the 

    <span style="color: #a40000; border: 1px solid #ef2929">字段</span>
into 
    <span style="color: #a40000; border: 0px solid #ef2929">字段</span>

for any NON-ASCII characters and charater "#".Help please.It is very annoying for the a NON-English user.
