### ISSUE TITLE
report a bug

### ISSUE THREAD

**Issue by Juddd** [Neftas/supplementary-buttons-anki#107]
I find the *Markdown* have some flaw in Androd client.This is my test card
```
* one
* two
* three
```
It is can show normally in my PC client like

![](http://i.stack.imgur.com/hMV3m.png)

But it can not show normally render in Andriod client.

**Comment by Neftas** [comment]
Hi @Juddd: I am not the developer of whatever Android client you are using. Therefore, I am not in a position to respond to bug reports. Please take this issue up with the developers from your Android client. (If you are using AnkiDroid: I've checked this myself, and bullet lists show up correctly).
