### ISSUE TITLE
dysfunctional text highlight button

### ISSUE THREAD

**Issue by ceortiz** [Neftas/supplementary-buttons-anki#11]
I am able to highlight the text i want to highlight but when I check the flashcards I have made and start reviewing them most of the cards are not highlighted. Please help. I really value your effort in making this addon. i've gone to this extent of writing to you because i know this feature of highlighting text is really indispensable. your response would be greatly appreciated. Thanks in advance.

**Comment by Neftas** [comment]
Highlighting text now works confirmed on Linux and Mac OS X. Don't know about Windows, can anyone tell me?

**Comment by Neftas** [comment]
Removed highlighting again on everything that isn't Linux 43286080748cde7d7a09f9bb47837a78c8bb4097 and won't add it again.

**Comment by Neftas** [comment]
Fixed in faa9e2c672fa8177d2968569df9dab32e5b3a8a9.
