### ISSUE TITLE
Some keyboard shortcuts not working

### ISSUE THREAD

**Issue by malore** [Neftas/supplementary-buttons-anki#116]
I don't know if Power Format Pack is conflicting with other addons (I have AdvancedPreviewer, AnkiConnect, AwesomeTTS, Batch Note Editing, Hierarchical Tags, Image Occlusion Enhanced, ir Addon, Night Mode, Review Heatmap, Search and Replace Tag and Tag Toggler installed) but some keyboard shortcuts don't work. In particular the shortcuts for indenting or outdenting, making a horizontal rule, creating lists don't work, while the others work.

**Comment by Neftas** [comment]
Hi @malore, you can change the keyboard shortcuts for this add-on from within Anki itself. Go to _Tools > Power Format Pack (options) > Keybindings..._ and knock yourself out.

**Comment by malore** [comment]
@Neftas I don't manage to do it. Wherever combination I press nothing happens.

**Comment by Neftas** [comment]
@malore Have you read the documentation? You have to double-click the shortcut that you want to change, then you can enter a key combination.

**Comment by malore** [comment]
@Neftas Thank you, I read documentation very quickly, actually. I found out the problem: these keybindings don't work with Italian keyboard. Thank you again.

**Comment by Neftas** [comment]
@malore I'm glad you sorted it out.
