### ISSUE TITLE
Source code displaying incorrectly 

### ISSUE THREAD

**Issue by ClassicLean** [Neftas/supplementary-buttons-anki#122]
## What is the problem? 
![1](https://user-images.githubusercontent.com/25625119/39129676-ab04d282-473d-11e8-850d-eab0fdccda0d.png)
Source code displaying incorrectly 

## How can we reproduce the problem?

1. Create a card
2. Go to markdown mode
3. Type this:
    :::java
    public class Test { }

What were you doing when the problem occurred?

1. I tried to recreate it again
2. I tried using the codeblock button but I ended up with the same result

## What was the expected behavior? 
Something that would look like a markdown source code from discord would be ideal since I have no idea what a markdown source code from Anki looks like at the moment.

**Comment by Neftas** [comment]
You might want to first type your Markdown and only then convert it using the Markdown button. So: 

0. Markdown mode is not active, so the background is not yellow.
1. Type your markdown, for example:
    
        ```java
        public class Test {}
        ```
2. Click the Markdown button.
3. See something like this:

    ```java
    public class Test{}
    ```
