### ISSUE TITLE
nested lists not "nesting" correctly

### ISSUE THREAD

**Issue by rjgoif** [Neftas/supplementary-buttons-anki#23]
(_HTML line breaks added for ease of reading_)
if I start with a ordered list:

```
<ol>
    <li>item 1</li>
    <li>item 2</li>
    <li>item 3</li>
</ol>
```

and I select each line and press `Ctrl+Shift+C` on each line, I correctly end up with:

```
<ol>
    <li>{{c1::item 1}}</li>
    <li>{{c2::item 2}}</li>
    <li>{{c3::item 3}}</li>
</ol>
```

However, this breaks down when I try nested lists. From the above, I try to make a nested list by pressing `Enter` after line 1, then indenting with `Ctrl+Shift+]`. I make my list items and end up with:

```
<ol>
    <li>item 1</li>
        <ol>
            <li>sub a</li>
            <li>sub b</li>
            <li>sub c</li>
        </ol>
    <li>item 2</li>
    <li>item 3</li>
</ol>
```

What I _should_ end up with is:

```
<ol>
    <li>item 1
        <ol>
            <li>sub a</li>
            <li>sub b</li>
            <li>sub c</li>
        </ol>
    </li>
    <li>item 2</li>
    <li>item 3</li>
</ol>
```

This has implications when cloze deleting lists, as the }} brackets placed by Anki will cut off parts of the list HTML and corrupt the overall structure. This topic is covered with supporting links [here](www.w3.org/wiki/HTML_lists). I haven't found an easy workaround that doesn't involve manual HTML editing.

**Comment by Neftas** [comment]
Hey @rjgoif, thanks for taking the time to report this behavior.

Am I correct that you want to cloze-delete an entire list? As in, selecting a sublist of multiple elements and then press the cloze-delete button? If so, could you provide an example of current and desired behavior? If that is not what you meant, can you expand a little on the issue?

As it stands, I don't believe that truly nested list are possible without manually editing the HTML. The add-on uses the built-in JavaScript engine (the same you see around the web in rich-text editors), so it's standard behavior and outside of my influence, unfortunately.

**Comment by rjgoif** [comment]
What I would like to happen is:

    <ol>
        <li>{{c1::item 1
            <ol>
                <li>sub a</li>
                <li>sub b</li>
                <li>sub c</li>
            </ol>}}
        </li>
        <li>{{c2::item 2}}</li>
        <li>{{c3::item 3}}</li>
    </ol>

I looked into this further and found that the issue is with BeautifulSoup, which is set by default to not allow any `<ol>` or `<ul>` tags to exist without first closing any outstanding `<li>` tags. When Anki runs the HTML through BeautifulSoup before adding the cloze deletion brackets, it adds the offending `</li>` automatically. I wrote an add-on that seems to prevent this reasonably well. It can be found [here](https://ankiweb.net/shared/addons/)

**Comment by Neftas** [comment]
Nice catch! Is it possible for you to post the code of your add-on on GitHub so I can take a look? By the way, you link to the general add-on page, not to your add-on specifically.

The lists are created in JavaScript. Anki and the Power format pack use some standard web API functions that you'll find [across the internet](https://developer.mozilla.org/en-US/docs/Web/API/document.execCommand). 

JSON is used in Python to serialize and deserialize structures (just like pickle). In Anki and the Power format pack it is used - among other things - to dump strings into JavaScript functions.

**Comment by rjgoif** [comment]
I can write entire code in this comment, as it's very, very simple.

    import BeautifulSoup
    new_NESTABLE_LIST_TAGS = { 'ol' : ['li'],
    						'ul' : ['li'],
    						'li' : ['ol', 'ul', 'dl'],
    						'dl' : ['li'],
    						'dd' : ['ul', 'ol', 'dl'],
    						'dt' : ['ul', 'ol', 'dl'] }
    
    BeautifulSoup.BeautifulSoup.NESTABLE_LIST_TAGS = new_NESTABLE_LIST_TAGS
