### ISSUE TITLE
Ctrl+H for history not working properly when addon is running

### ISSUE THREAD

**Issue by eulerreich** [Neftas/supplementary-buttons-anki#36]
In the add window, the correct behavior for ctrl+h is that a list of previous cards popup where the "history" button is on the lower right. The behavior of ctrl+h with this addon is that you have to press ctrl+h several times for the add window to focus on the "history" button and then one more time for the history window to pop up.

**Comment by eulerreich** [comment]
I see in your code that ctrl+h was assigned to horizontal rule. I fixed it by changing the binding in the code, but I would still suggest changing it since it conflicts with Anki's native binding for history.

**Comment by Neftas** [comment]
Thanks for reporting this issue. It is indeed conflicting, and I will change the shortcut key. If you notice other conflicts, please report them here, even if you can figure out how to change it in the source code. That will make the addon better for everyone else as well :)

**Comment by Neftas** [comment]
Fixed in 78686009633cd54cddbbc9c5f8cc15b1c90dcc39.
