### ISSUE TITLE
Blockquote with cite

### ISSUE THREAD

**Issue by trehehaeuser** [Neftas/supplementary-buttons-anki#37]
Hello, I want to insert the cite-tag into a blockquote. How can I do this? Best regards Tom

**Comment by Neftas** [comment]
Can you give an example of desired behavior?

**Comment by trehehaeuser** [comment]
An example in HTML:
<blockquote>
 <p>I contend that we are both atheists. I just believe in one fewer
 god than you do. When you understand why you dismiss all the other
 possible gods, you will understand why I dismiss yours.</p><cite>Stephen Roberts</cite>
 </blockquote>

Thanks for your efforts!

**Comment by Neftas** [comment]
I've added the functionality you requested (c0956c04894cce23296171a1522b184ea9be2277). You can now add an author to the blockquote. To do so, put the author's name between brackets:

    This is a quote. [[Nobody]]

Please update the addon from the Anki addon site.
