### ISSUE TITLE
A separate line of toolbar (enhancement)

### ISSUE THREAD

**Issue by AgarwalPragy** [Neftas/supplementary-buttons-anki#38]
This addon adds a ton of shortcuts to the add window, all next to the original shortcuts. This makes it impossible to work with if the add window is not full screen(or appropriately sized).
It will be nice to have a wrap feature that automatically moves buttons to next line if the window is not wide enough.
![image](https://cloud.githubusercontent.com/assets/7423639/8946913/93335c5e-35b2-11e5-9d73-e7c1834b469a.png)

**Comment by Neftas** [comment]
Thanks for taking the time to request a new feature. I will look into it when I find some time.

**Comment by Neftas** [comment]
I've addressed this enhancement in 9bbca2f. You can now select to put the extra buttons above the original buttons, below them, or (default) next to them. You can download the new version from AnkiWeb.

**Comment by AgarwalPragy** [comment]
Awesome!
