### ISSUE TITLE
Ordered lists not working correctly

### ISSUE THREAD

**Issue by allenm518** [Neftas/supplementary-buttons-anki#40]
Hello, in trying to create ordered lists, the nests do not occur correctly:
If it start with 1. and try and indent the next line to get A., I only get 1.
If I start with A. and indent the next line, I get 1. but then next indentation is also 1.

If I try to change an indent style with the ordered list button, it changes the whole list to what I have selected and removes all the indents.

Is this normal function?

Thanks for your work, i enjoy being able to add the bullet lists

**Comment by Neftas** [comment]
Thanks for taking the time to report this.

I have investigated the issue. First, to have an ordered list like:

    A.
        A.
            I.

or whatever, indent the second (and third etc.) level of your list **two times**, then press the `Create ordered list` button again and select your ordered list of choice.

I am not sure I understand your second issue. The `Create ordered list` is a toggle button. That means that one click adds styling, while a second click removes styling. So selecting an ordered list and clicking the `Create ordered list` button should result in the removal of the list (and only text remaining). I noticed that selecting a complete list with multiple levels and toggling `Create ordered list` will only remove the first level.

So to change the style of the list you first undo the list by clicking `Create ordered list` and selecting whatever you like. You'll notice that the list is gone. Then click the button a second time and choose the styling of your choice.

I hope this explains this admittedly odd behaviour.
