### ISSUE TITLE
Option to assign custom keyboard shortcuts

### ISSUE THREAD

**Issue by glutanimate** [Neftas/supplementary-buttons-anki#41]
First of all, thanks a lot for developing this add-on. It has made working with Anki much more streamlined for me.

One thing that keeps bothering me, though, is the choice of keyboard shortcuts. As I am not using a US QWERTY layout, hitting combinations like 'Ctrl + Shift + [' requires quite a lot of finger acrobatics:

![](https://i.stack.imgur.com/HsJsk.png)

With that in mind it would be fantastic to have a keyboard shortcut selection screen in the options menu.

Thanks for giving this feature request your consideration.

**Edit**: I have [manually adjusted](https://github.com/Glutanimate/supplementary-buttons-anki) my keybindings for the time being, but I think it would still be very useful to have an easy way of configuring this, especially for less technically-minded users.

**Comment by Neftas** [comment]
Hi @Glutanimate, thanks for taking the time to open this issue. I will take a look at this issue as soon as I will have some time for it, I have been quite busy with my job and life :). If you feel this is something that you can implement yourself, don't hesitate to create a pull request.

**Comment by Glutanimate** [comment]
Thanks for the reply, @Neftas. I absolutely understand.

**Comment by Neftas** [comment]
I added user-defined keyboard bindings (c0956c04894cce23296171a1522b184ea9be2277). Please update the addon.

**Comment by Glutanimate** [comment]
Awesome! Working well here so far. 

My only remaining request would be to add support for Unicode characters, if possible. Without a QWERTY keyboard layout the shortcut choices can become very limited, especially given how many combinations are already taken up by system shortcuts and default Anki bindings.

**Comment by Neftas** [comment]
I will look into it when I get a chance :)

**Comment by Neftas** [comment]
Hi @glutanimate, in a recent release I have reworked the custom keyboard shortcuts. You can now change them from within Anki itself by going to _Tools > Power Format Pack add-on (options)... > Keybindings..._ It should now also be possible to assign Unicode keyboard shortcuts, but I haven't been able to do extensive testing on this. Could you possibly give this a try and tell me if that works for you? Thanks!

On a sidenote, I also noticed you have created a YouTube video on this add-on. Awesome! This actually inspired me to do some outstanding work on the add-on, including the newly created custom keyboard shortcuts dialog. I will include a link to your YouTube video in the description of the add-on. Cheers :)

**Comment by glutanimate** [comment]
Hey @Neftas, thanks for letting me know! I've just had the chance to give the new version of PFP a trial run and it's working beautifully. Had no trouble at all to assign all of my favorite umlauts to different actions. Great job! I've pinned a comment on my video that advises users about this new feature (I would have set an annotation, but it looks like YouTube have dropped support for that).

About the video: The pleasure is mine! I was more than happy to spread the word about your add-on. Not only has it been a major staple in my flashcard creation process, but it has also proven incredibly helpful as a reference point for my own add-ons time and time again. In fact, just yesterday I was able to implement a far more robust inline data format for my [Internal References add-on](https://github.com/glutanimate/internal-references) by looking at how PFP handled markdown.

Thanks again for all the work you've put into this project. It's quite an honor that you'll be including my video in the add-on description :). Thank you for that as well.

**Comment by Neftas** [comment]
That's good to hear! And looking at the timestamp of this issue, it only took me two years to implement ;-)

When I first started with this add-on, I used another one ["Syntax Highlighting for Code"](https://ankiweb.net/shared/info/1463041493) for inspiration and as a cheat sheet. And more recently, I have also taken a look at your add-ons, and immediately found useful stuff that I hadn't even thought about. That is what is great about open-source software, you can learn so much just by reading each other's code. So, I have to thank you as well!
