### ISSUE TITLE
How to get out of a <code> or <pre> tag?

### ISSUE THREAD

**Issue by Juddd** [Neftas/supplementary-buttons-anki#42]
(sorry my poor English.)I can use the button of "create a code block" or "code format text" to write my code,but,,,,How can I stop the status to write the normal font??It confuse me long time.Help me,please.

**Comment by Neftas** [comment]
Hi there! When you create a code block at the end of your text, you can't actually exit it, unless you edit the HTML directly. This is unforunately different from making text bold, where you can just press the button a second time and you are back in normal mode, and is more like text coloring: once you activated it at the end of your text, it will keep coloring everything you enter. As a workaround, I use the formatting-removal button to get out of code blocks, so: type some text that should not be formatted as code, and press the formatting-removal button. The text you type after won't be formatted as code. I hope this helps.

**Comment by Juddd** [comment]
@Neftas So would you like to help us develop this feature as making text bold?Even the text background-coloring?I think it is very practical and I look forward to that much too.

**Comment by Neftas** [comment]
You are right that by using the format-removal button you are also removing inline elements and need to reapply the inline styling. You can use the HTML editor and remove the tag by hand if you don't want to restyle. You can remove the background color by selecting the default background color from the popup. I will investigate what can be done, but I won't make any promises, and it might take a while.

The picture you are showing looks like a lot of `<pre>` tags one after the other? Is there a reason you wouldn't put all the code in a single `<pre>`? That would get rid of the borders around every line of code.

If you use code a lot in your cards, you should consider using a dedicated code highlighting plugin, like [Syntax Highlighting for Code](https://github.com/tmbb/SyntaxHighlight). That's the one I use, as well.

**Comment by Neftas** [comment]
You can now use Markdown to format your code blocks.
