### ISSUE TITLE
"Code format text" button shortcut conflicting with Anki's own shortcuts on OS X.

### ISSUE THREAD

**Issue by TimothyBramlett** [Neftas/supplementary-buttons-anki#43]
First off, fantastic add on!  I love it!

I am having one problem on OS X though or maybe I am just doing something completely wrong.  The shortcut key to insert code formatted text is supposed to be command + , on OSX but when I hit that key combo it actually brings up Anki's preferences menu! :)

Is there some way to get it mapped to a new key combo?

**Comment by Neftas** [comment]
Hey @TimothyBramlett, thanks for the kind words!

And good catch, you're absolutely right that this shortcut conflicts with the shortcut that Apple reserves for preference menus. If I changed all shortcuts for the Mac to use the <kbd>Ctrl</kbd> button instead of <kbd>Cmd</kbd> (just like on Linux and Windows), would that help? (I don't own a Mac, so if you could see if this somehow would conflict with anything, I'd appreciate the heads-up :)

**Comment by TimothyBramlett** [comment]
@Neftas That might work.  Let me mess around with my Mac tonight and see if there would be any issues in doing that!  I will get back with you! :)

**Comment by TimothyBramlett** [comment]
@Neftas I tried pressing control + , in Anki and it seems to actually insert a 1/4 symbol into the field.  So I assume some feature is mapped to that shortcut combo.

**Comment by Neftas** [comment]
Great, thanks for testing!

I'll tell you what I'll do. I'll get my hands on a Mac and see what shortcuts are not yet taken, and propose a couple of them here. Might be a couple of days, but I'll get back to you!

**Comment by TimothyBramlett** [comment]
@Neftas, perfect!  Maybe you can map it to ```command``` + ```shift``` + ```,```.  Playing around with that just now in Anki and there doesn't seem to be any thing mapped to that key combination that I could detect.

**Comment by sursh** [comment]
:100:  was about to open this issue. And :100:  `command+shift+,` would work fine.

**Comment by TimothyBramlett** [comment]
@sursh :)

**Comment by Neftas** [comment]
I've added user-defined keyboard bindings, so you can now change the keyboard bindings yourself if you find that the default ones do not work (c0956c04894cce23296171a1522b184ea9be2277). Please update the addon.

**Comment by sursh** [comment]
Thanks @Neftas !

**Comment by TimothyBramlett** [comment]
Thanks!
