### ISSUE TITLE
I'm not sure how to get <code> or <pre> blocks to work

### ISSUE THREAD

**Issue by pschroeter** [Neftas/supplementary-buttons-anki#48]
I was hoping I could use this add on to apply multiple formats to selected text with the click of a button. I use the Extras field in my cloze cards to write extra non-essential information to myself in three different font sizes in italics. I thought I could use your add-on to link to one of the classes I added to the Styling section of Card Types. All I have been able to get these button to do is make the text look like it was created on a typewriter.

I have this in my Styling section of Card Types

    .c { font-size: 15pt; font-style: italic; }

This only works if I wrap text in the HTML editor in `<span class=”c”>` and I’m not sure if your add-on does something else. I’m not sure how to get `<code>` or `<pre>` blocks to work, if I can get them to work at all. I fully admit I don’t really understand CSS at all.
Thank You

**Comment by Neftas** [comment]
Hi @pschroeter!

Thanks for using the add-on and taking the time to open this issue.

The `<code>` tag in HTML is meant to be used to represent pieces of computer code, i.e. pieces of a programming syntax. I wouldn't recommend to use it for anything else. You might use it on a card like this, for example:

> Create two variables in Perl, named `a` and `b`.

The thing with using the `<code>` tag for anything else is that, as you have noticed, it doesn't look nice as you have noticed and lines wrap in a funny way.

The `<pre>` tag is meant to represent preformatted text. This is handy if you want to see the text you entered with white space intact and without word wrapping. I use this to make blocks of computer code, but you could use it for anything if you need white space to be represented just the way you entered it. Without using CSS, inserting `<pre>` will result in text being in typewriter font, just as you noticed.

The functionality that you are looking for, using different font sizes, is currently not implemented. I **am** working on a Markdown implementation which should land in the next couple of weeks. That will make it possible for you to write:

    This text has a different font that the rest of the text.
    {: .bigger-font}

This will be converted to

    <p class="bigger-font">This text has a bigger font than the rest of the text.</p>

And you can then put whatever formatting you want in your CSS `.bigger-font`.

**Comment by Neftas** [comment]
Markdown is implemented in version 0.8 of the addon. You can download it from Ankiweb. So now you can use the syntax I described above.
