### ISSUE TITLE
Custom Study Sessions

### ISSUE THREAD

**Issue by gistgist** [Neftas/supplementary-buttons-anki#50]
In night mode it's very difficult to read "special" decks or annoucements (i.e. custom study sessions or the message anki gives about too many decks).
Is there a way to change the color of this text (either via Anki settings or night mode)?

Image attached, see deck titles on lefthand side
<img width="507" alt="screen shot 2015-10-27 at 2 33 54 pm" src="https://cloud.githubusercontent.com/assets/15349336/10770166/ceedc40e-7cb7-11e5-8327-e16c0440de1b.png">

**Comment by Neftas** [comment]
I'm sorry, is this related to Supplementary Buttons for Anki? I would advise you to contact the maintainer of the the addon that brings you night mode, as I can do very little to change an addon I didn't create.

**Comment by gistgist** [comment]
Oops yes, posted to wrong group. Thanks
