### ISSUE TITLE
hyperlink not working for "file:///"

### ISSUE THREAD

**Issue by rdiaz02** [Neftas/supplementary-buttons-anki#52]
I think creating a hyperlink does not do what we would expect if the "Link to" is
`file:///some_path`

What would I expect? That this is, for instance, dealt with in a Linux system using xdg-open (so that the file is opened by whatever program you have configured). For example
`file:///tmp/some.pdf`
would fire up whatever I have configured to open PDFs.

(But then, maybe this is not what hyperlinks are intended for in this add-on ).

**Comment by Neftas** [comment]
Good catch. I've implemented a rather naive version, where it assumes that all hyperlinks use the HTTP protocol. I will take a look at what can be done.

**Comment by rdiaz02** [comment]
The reason is in function `insert_anchor` in Hyperlink.py. The `http`is added by force.

**Comment by rdiaz02** [comment]
I've played defining a new buttom and shortcut, which I called hyperlink2, that just adds any text, so any URI, in a `<a href=` without prepending the `http://`. I've just sent a pull request.

**Comment by Neftas** [comment]
@rdiaz02 awesome that you actually took the time to make a pull request.

However, I don't think adding an extra button is a good idea for this functionality (there are too much buttons already). You are correct in stating that I hard-coded the `http://`-prefix when using the hyperlink button. So, I think a fair approach would be to just delete that part of the code, and let users themselves decide what to put into the anchor, just like you suggested.

Thanks for taking the time to make improvements to this addon, it is appreciated!

**Comment by Neftas** [comment]
Fixed in 14913d0feb3bb1d6af75b5b5b7c7d57596736534. You can update from AnkiWeb.

**Comment by rdiaz02** [comment]
Great, thanks. I just checked, and it works perfectly.

(Yes, you are right, the new extra button was an overkill but I also did not want to remove the `http://` prefix as it might have been there for a reason I did not know).

I am closing the issue.
