### ISSUE TITLE
How to set up Code Syntax Highlighting?

### ISSUE THREAD

**Issue by MikeLeonard** [Neftas/supplementary-buttons-anki#55]
Sorry not an issue with the code exactly... but I'm having trouble getting the syntax highlighting to work and would really appreciate a bit of help as I'd like to use Anki improve my programming skills.

I'm new to Python but have installed 'Pygments' using 'conda install Pygments'. I've set my $PYTHONPATH variable to the /bin/python inside my anaconda directory.

On http://pygments.org/ I can see that what the following Python lines should look like (ie they have colour highlighting...)

``` python
def print_me(this):
    print "Printing: ", this
```

This is the example given on the add-on page here: https://ankiweb.net/shared/info/162313389

I'm clicking the '{}' button (Cmd Shift + on a Macbook) and it correctly formats the code into a nice code block font. This I can make do with of course, but I'd love the colour highlighting. Is there something I'm doing wrong or something I can try to get this working?

Thanks a lot in advance!

Mike

**Comment by Neftas** [comment]
Hi @MikeLeonard, the syntax you're referring to is part of the Markdown package. So indent your code four spaces, use three colons to indicate the language and toggle the Markdown button.
Something like this will work and color the syntax:

    :::python
    class C(object):
        def __init__(self):
            pass

**Comment by skotzko** [comment]
@Neftas is there a way to change the CSS applied when using the Markdown code highlighting? It's working fine for me, but having a hard time seeing what classes are being applied to the code by Pygments.

**Comment by Neftas** [comment]
@skotzko you mean the code between single backticks? It has not got any CSS class associated with it and I don't think it's getting rendered by pygments, it is just the basic rendering of `<code>` elements by QtWebKit. I use the following to style these elements:

    code:not([id='typeans']) {
        color: #268bd2;
        background-color: #eee8d5;
        padding-left: 5px;
        padding-right: 5px;
        border: 1px solid;
        border-color: lightgrey;
        border-radius: 5px;
        white-space: nowrap;
    }

(You'll have to exclude `#typeans`, otherwise it will apply the formatting to native Anki elements as well.)

**Comment by skotzko** [comment]
@Neftas ah, perfect. I wasn't sure what the right selector was. All set now, thank you!

**Comment by dayFun** [comment]
Any ideas/suggestions on how to enable cloze deletions in code formatted blocks? 

Currently, if I create a card with cloze deletions and then apply the syntax highlighting, the cloze also gets formatted and then Anki does not recognize it as a cloze deletion.

With mixed results, I have manually fixed (removed) the formatting on the cloze itself, sometimes this works and other times it does not.

Any feedback would be greatly appreciated.

Thanks for everything!

**Comment by badlydrawnrob** [comment]
@Neftas Could you confirm the Markdown code blocks _aren't_ using [Pygments](http://pygments.org) when rendering in study mode? I thought one of the Power Format Pack features was to give syntax highlighting similar to the [live pygments demo](http://pygments.org/demo/6036755/)?

Also, I'm having the same issue as @dayFun — The `{{cloze::deletion}}` only works if you add the code block after it's been converted from Markdown.

<img width="621" alt="screen shot 2016-09-20 at 17 52 28" src="https://cloud.githubusercontent.com/assets/1176875/18678035/0b351be6-7f5b-11e6-9750-8b039e12e709.png">

**Comment by Neftas** [comment]
@badlydrawnrob I thinks there is some confusion here about terminology: the larger *code blocks*, the ones started by three backticks <code>```</code> or three colons <code>:::</code> are syntax highlighted by Pygments, but *inline code "blocks"*, the ones between single ticks (<code>`</code>) are not being rendered by Pygments, so you have to style them yourself.

**Comment by Neftas** [comment]
@badlydrawnrob Your second issue has been addressed before in #74. Allowing changes in rendered Markdown can (and probably *will*) mess up the formatting of your card when you go back to Markdown mode.

**Comment by badlydrawnrob** [comment]
@Neftas Ah ok thanks for that. So we can style with CSS by outputting the [standard pygments styles](https://github.com/richleland/pygments-css)? Still working my way through the pygment docs! And on the second point, I'll try and use the workaround mentioned in #74

**Comment by badlydrawnrob** [comment]
@Neftas In answer to my own question, no wonder I'm having difficulties styling pygments. It looks like you're hard-coding the spans instead of using the proper classes, i.e. [`<span="k">` for keywords](http://pygments.org/docs/quickstart/#example). I had to output the notes as plain text to see what was going on:

```html
"<div class=""codehilite"" style=""background: #f8f8f8"" align=""left""><pre style=""line-height: 125%""><span style=""color: #000000"">count</span> <span style=""color: #ce5c00; font-weight: bold"">=</span> <span style=""color: #0000cf; font-weight: bold"">0</span>  <span style=""color: #204a87; font-weight: bold"">while</span> <span style=""color: #000000"">count</span> <span style=""color: #ce5c00; font-weight: bold"">&lt;</span> <span style=""color: #0000cf; font-weight: bold"">10</span><span style=""color: #000000; font-weight: bold"">:</span>     <span style=""color: #204a87; font-weight: bold"">print</span><span style=""color: #000000; font-weight: bold"">(</span><span style=""color: #000000"">count</span><span style=""color: #000000; font-weight: bold"">)</span> </pre><pre style=""line-height: 125%""><span style=""color: #000000; font-weight: bold"">    </span>&nbsp;{{c1::count += 1::What fixes this code?}}</pre></div>
```

So for now, this feature is unusable for me, as the whole point of pygments is to allow easy switching of themes — something I'm trying to offer for my [Anki programming themes](https://github.com/badlydrawnrob/anki)

This seems like bad practice to me, no?

**Comment by vtpros** [comment]
I'm having the same problem with highlighting. For instance I put this code in the card.
<pre>```python
def color_all_the_things():
    return None
```</pre>
But when I press Ctrl + . (or a button), there's no highlighting, and it looks [like this](http://image.prntscr.com/image/aff00dae531147558dd5b53e3318a732.png)

Do I have to install something else, apart from this add-on?

**Comment by Neftas** [comment]
@vtpros Please enable Markdown in the add-on options. This will make the Markdown button appear in the the editor.

**Comment by vtpros** [comment]
@Neftas Or, I see now. Thank you!
