### ISSUE TITLE
How to get rid of space before lists?

### ISSUE THREAD

**Issue by dsia** [Neftas/supplementary-buttons-anki#56]
Hi,
Love the add-on especially the indent and list. However, is there a way to get rid of the line space before a lists starts? That would make the list much tighter. 

Thanks for helping

**Comment by Neftas** [comment]
Yes, you could probably use CSS to change how your lists look. Use the style sheet of your cards and specify the desired behavior.

**Comment by gsapu** [comment]
Edit card > card style

Add following to Style:
`table {
 margin:0px auto 0 auto;
 text-align:left;
}`

Also, wrap in a <table> the Back (Back Template)
`{{FrontSide}}

<hr id=answer>

<table>
   <tr>
      <td>
         {{Back}}
      </td>
</tr>
</table>`

See below:

![screen shot 2016-06-26 at 14 12 02](https://cloud.githubusercontent.com/assets/7359939/16362497/3e8fd806-3ba8-11e6-8ab3-519b717f8af4.png)

![screen shot 2016-06-26 at 14 14 17](https://cloud.githubusercontent.com/assets/7359939/16362499/4d0d02aa-3ba8-11e6-9043-845afff7adac.png)
