### ISSUE TITLE
Error on Installation: "unindent does not match any outer indentation level"

### ISSUE THREAD

**Issue by tom-newhall** [Neftas/supplementary-buttons-anki#59]
Hi after I installed this plug in, I got the following error when I re-opened anki:

"""
An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "aqt/addons.pyc", line 41, in loadAddons
  File "/Users/Tommy/Documents/Anki/addons/Supplementary Buttons Anki.py", line 2, in <module>
  File "/Users/Tommy/Documents/Anki/addons/extra_buttons/extra_buttons.py", line 40, in <module>
  File "/Users/Tommy/Documents/Anki/addons/extra_buttons/markdowner.py", line 43
    self.editor_instance                = other
                                              ^
IndentationError: unindent does not match any outer indentation level
"""

Also under Tools>Addons this plugin is listed as "Supplementary Buttons Anki" rather than "Power format pack"

Anyway, if anyone knows what is going on, I'd appreciate the help.

I'm running Anki on mac OSX 10.11.2

Tom

**Comment by Neftas** [comment]
Hi @tom-newhall, thanks for reporting this!

This was a bug, which should be solved now in 75cba11. You can download and reinstall the latest version from AnkiWeb.

**Comment by tom-newhall** [comment]
Excellent! It works beautifully!
I do have two feature-request type questions though...
First of all... I mainly downloaded this extension so I could have a simple way to make tables in Anki. I noticed that when making a table, it automatically formats them with a nice blue line etc., but I'd really like to just have a plain table, and then do the formatting myself with CSS in the cards. I opened up the code and thought I got rid of all the stuff that looked like like the table formatting inside the "table.py" file, and saved it, but it still includes the formatting when I use this feature. Any Suggestions for how to make it so that there is no formatting in the HTML a table is created from text?

Second, I think because  I have another plugin that adds buttons to the toolbar, the buttons for your plugin are all jammed together as in the image below: 
![screengrab for anki buttons](https://cloud.githubusercontent.com/assets/16577804/12163380/598c36b4-b4ca-11e5-9034-b818491856e7.jpg)

I is there any way to move the buttons to the top line, next to the default Anki buttons, or otherwise mitigate this problem. 

Thanks for your quick response!

Tom

**Comment by Neftas** [comment]
As to point of formatting the table to your liking: I would suggest using Markdown to build your tables. You will get a "bare-bone" table that you can style with CSS, and the table will be more flexible as well, because you can easily edit the Markdown and update your table. 

As to your second point: [somebody already a feature request for this exact enhancement](https://github.com/Neftas/supplementary-buttons-anki/issues/38). When I find the time (real life keeps interfering :) ), I will definitely take a look at it, because on your screenshot the buttons look unusable.

**Comment by uitalo** [comment]
Hi, I have this error:
"Um erro ocorreu em um complemento.
Por favor, publique isto no fórum do complemento:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\anki\build\anki2\out00-PYZ.pyz\aqt.addons", line 41, in loadAddons
  File "C:\Users\cassio\Documents\Anki\addons\Supplementary Buttons Anki.py", line 2, in <module>
    import extra_buttons.extra_buttons
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\extra_buttons.py", line 41, in <module>
    from anki_modules.aqt import editor as myeditor
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\anki_modules\aqt\editor.py", line 11, in <module>
    from utility import Utility
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\utility.py", line 35, in <module>
    import markdown
  File "C:\Users\cassio\Documents\Anki\addons\extra_buttons\markdown\__init__.py", line 40, in <module>
    from ..python_modules import importlib
ValueError: Attempted relative import beyond toplevel package"

**Comment by tom-newhall** [comment]
Neftas,

Thanks for your response. I had tried getting tables in markdown working, but had trouble with it. I was able to get a table made with the following formatting:
```
 First Header  | Second Header
-|-
 Content Cell  | Content Cell
```

However, when I deleted the `-|-` on the second line, it did not render as a table. Once again, it's a minor issue, but I'd prefer not to have to add `-|-` after the first line. Ideally, I'd like something like this:
```
First Header  | Second Header
Content Cell  | Content Cell 
```

To produce the HTML like this:
```
<table>
<tr><td>First Header</td><td>Second Header</td></tr>
<tr><td>Content Cell</td><td>Content Cell</td></tr>
</table>
```
According to the documentation, it seems like this should work in markdown as well, but for whatever reason, I'm having trouble with it.

(From the manual:)
>The -|- part is optional, but can be used to align the column to the left (:-), right (-:) or to the center (:-:). You can skip this line completely, but do make sure you add a pipe character | between elements to designate a border.

Thanks,
Tom

**Comment by Neftas** [comment]
Hi @tom-newhall,

The Markdown syntax is different from the syntax I used for the table button. For Markdown to work, the second line is mandatory. You can look the syntax for Markdown up on the internet.

**Comment by Neftas** [comment]
@uitalo could you please open a separate bug report? And please specify what you were trying to do, what happened, and other details that might be important.

**Comment by Neftas** [comment]
@tom-newhall I have added a way to change the position of the buttons. You can update the addon on AnkiWeb.
