### ISSUE TITLE
Highlight words or inline sections within markdown

### ISSUE THREAD

**Issue by AGBrown** [Neftas/supplementary-buttons-anki#62]
Is it possible to highlight one or more words within a markdown formatted field?

I know with markdown itself we can do `**strong**`, but can we make one or more words within a paragraph bold, and also with a given highlight color?

I guess this could be possible with an [inline pattern](https://pythonhosted.org/Markdown/extensions/api.html#inlinepatterns) which generated a span with a custom class, but I don't know if that is possible on the current plugin.

Use case: highlight important words within answers using bold and a strong color so that they stand out when reviewing cards at speed. I do this a lot when using just html fields, but would like to do it in fields that are markdown and include code blocks.

**Comment by AGBrown** [comment]
Ah, I just found out that with a little fiddling I can define a css class (say `answer`) and do:

```This is a **test of highlighted**{ .answer } inline words```

Is this the best way to do what I want?

**Comment by skotzko** [comment]
@AGBrown yep, Pygments (the highlighting engine here IIRC) can process inline HTML. That means you can write little `span`s where needed (and use something like TextExpander if its common/repeated). 

For example, I just tried this in a card and it worked:

```
**this should be bold**
<span style="font-weight: bold; color:red;">this should be bold and red</span>
```

resulted in this output:

![screen shot 2016-01-12 at 5 05 45 pm](https://cloud.githubusercontent.com/assets/311226/12281889/beb5b6e0-b94e-11e5-907e-36eca61cd298.png)

**Comment by AGBrown** [comment]
Thanks. Is it possible to define an [inline pattern](https://pythonhosted.org/Markdown/extensions/api.html#inlinepatterns) within this plugin (I'm guessing that will do what I want)? I'm lazy and like to reduce keystrokes (which I guess is why I like markdown).

**Comment by Neftas** [comment]
I would use the `this **is**{ .className } text` syntax myself. But of course you can define your own custom classes, if you're willing to dive in and change some code in the addon yourself.

**Comment by AGBrown** [comment]
I had a quick look at [markdown/inlinepatterns.py](https://github.com/Neftas/supplementary-buttons-anki/blob/master/extra_buttons/markdown/inlinepatterns.py). I think that's where it would happen. I guess the idea would be to define patterns by a simple regex in a config file that people could edit.

If I have time I'll try and do a PR for it, but for the moment I'm sticking with `**text**{.myClass}` and autohotkey to make it easy with a keyboard shortcut.
