### ISSUE TITLE
List button indents last item

### ISSUE THREAD

**Issue by AGBrown** [Neftas/supplementary-buttons-anki#65]
Repro steps: I create a list of three items, with an italic word in the last item. I press <kbd>Ctrl</kbd> + <kbd>]</kbd>, and select the default list type. It creates the html (line breaks added for convenience):

<pre>&lt;ol>
&lt;li>one item&lt;/li>
&lt;li>two items&lt;/li>
&lt;li type="1" start="1" style="margin-left: 20px; ">three &lt;i>items&lt;/i>&lt;/li>
&lt;/ol></pre>

**Comment by Neftas** [comment]
Could you please include how you created the list in the first place? Did you edit the HTML directly? And what was the behavior you expected to see?

**Comment by AGBrown** [comment]
Creating the initial text was just a matter of entering a line of text and
hitting enter at the end of each one, but not at the end of the third line. Then
I highlighted a (the last) word in the last sentence and pressed Ctrl+i.

After that, Ctrl+a to select all text and then create the list as described
originally.


On Thu, Jan 21, 2016 at 6:49 p.m., Stefan van den Akker < notifications@github.com [notifications@github.com] > wrote:
Could you please include how you created the list in the first place? Did you
edit the HTML directly? And what was the behavior you expected to see?

—
Reply to this email directly or view it on GitHub
[https://github.com/Neftas/supplementary-buttons-anki/issues/65#issuecomment-173671746] .[https://github.com/notifications/beacon/AAH0phcDl8rXH6CU921StVlwhlxyd6E9ks5pcR_VgaJpZM4HJtzH.gif]

**Comment by Neftas** [comment]
Ah, so it only happens when the _last item_ ends with a tag. Interesting, and thanks for reporting!

**Comment by AGBrown** [comment]
> Ah, so it only happens when the last item ends with a tag.

It could well be that - I hadn't narrowed it down that far. Trying that out just now it seems that if the italics are not the last word in the last line then it doesn't seem to happen.

**Comment by Neftas** [comment]
Fixed in b2d6341. At the moment, not yet on AnkiWeb.

**Comment by trehehaeuser** [comment]
Hi Stefan,

how can I unsubscribe from the email list. I receive to many emails!

best,

Tom

**Comment by Neftas** [comment]
@trehehaeuser did you read the previous answer I wrote to your question? You can unwatch this repo on GitHub and you will not receive any updates anymore.

**Comment by AGBrown** [comment]
@Neftas - this seems to be fixed using the original test case.
