### ISSUE TITLE
Markdown mode - bullet list unrendering adds leading backslash

### ISSUE THREAD

**Issue by AGBrown** [Neftas/supplementary-buttons-anki#66]
Repro steps: write one line of text as follows (text as between the `^` and `$` characters, but not including them):

<pre>^- aaa$</pre>

Then trigger markdown mode using the markdown button, and then untrigger it using the same button. The text now reads:

<pre>^\- aaa$</pre>

Successive trigger and untrigger button clicks double the leading backslashes each time.

However, even on the first rendering the item does not render as a bullet list (ref https://daringfireball.net/projects/markdown/syntax#list ). Using `*` instead of `-` will cause a bullet to render, but I would expect markdown to allow `-` for a bullet list as well.

**Comment by Neftas** [comment]
This is fixed in bdcb8ba. As before, this is **not yet** on AnkiWeb, but feel free to grab the code here and test it.

**Comment by AGBrown** [comment]
@Neftas - the original test case now works for me.
