### ISSUE TITLE
Plugin crashes on startup: cannot import name downArrow

### ISSUE THREAD

**Issue by haitike** [Neftas/supplementary-buttons-anki#70]
I get this error when I launch anki with the plugin:

```
Traceback (most recent call last):
  File "/usr/share/anki/aqt/addons.py", line 41, in loadAddons
    __import__(file.replace(".py", ""))
  File "/home/haitike/Documentos/Anki/addons/Supplementary Buttons Anki.py", line 2, in <module>
    import extra_buttons.extra_buttons
  File "/home/haitike/Documentos/Anki/addons/extra_buttons/extra_buttons.py", line 27, in <module>
    from aqt.utils import downArrow
ImportError: cannot import name downArrow

```
I use Anki in Linux (Debian) and I have tested to delete the folder and reinstall the plugin, with the same result.

**Comment by Neftas** [comment]
You can solve this issue by updating to the most recent version of Anki. The version from the repositories are usually very outdated, so you are encouraged to download from the website.

**Comment by Neftas** [comment]
I've added some code to make the addon backwards compatible with older versions of Anki (65ef9d6). You can update the addon from AnkiWeb.

**Comment by haitike** [comment]
Thanks for the fast answer and fix,
