### ISSUE TITLE
Markdown does not correctly nest lists

### ISSUE THREAD

**Issue by steelwolf** [Neftas/supplementary-buttons-anki#71]
Markdown syntax should allow for adding spaces before ordered or unordered list items in order to create nested lists. However, this gets translated in the add-on to a single non-nested list. This appears to be occurring with ordered lists as well as unordered lists.

Example:
```
* Item 1
* Item 2
 * Item 2a
 * Item 2b
* Item 3
```
Should look like:

> * Item 1
> * Item 2
>  * Item 2a
>  * Item 2b
> * Item 3

However, it is translated as:

> * Item 1
> * Item 2
> * Item 2a
> * Item 2b
> * Item 3

This is a different nesting issue than the one described in #23.

**Comment by Neftas** [comment]
Have you tried indenting the nested list with four spaces instead of two?

**Comment by steelwolf** [comment]
Thank you for the suggestion: Using four spaces instead of one does work. Is this intended? Typically you only need to add one space before the asterisk in Markdown to get nested lists (for example, creating lists here on GitHub).

**Comment by Neftas** [comment]
There is no single specification for Markdown. Some implementations do this, others do that. I'm using the implementation provided by the Python Markdown Project, and they decided on four spaces for indentation. So yes, it is intended, but the decision wasn't mine :)

**Comment by steelwolf** [comment]
Thank you for the clarification! Sorry about that.

**Comment by Neftas** [comment]
Don't worry about it :)
