### ISSUE TITLE
Cloze deletions and markdown mode?

### ISSUE THREAD

**Issue by prbroadfoot** [Neftas/supplementary-buttons-anki#72]
If I write a card in markdown, add some cloze deletions, then hit the markdown button, the cloze deletions do not work.

On the other hand if I write the card with markdown, hit the markdown button, then manually type cloze deletions (since the cloze button does not work), it looks like they do work. However, this process is more inconvenient and harder to edit. Is there another way?

**Comment by Neftas** [comment]
Yes, I tried to explain this in the documentation on AnkiWeb. When you push the Markdown button, you enter a mode I like to call "Markdown mode". You are not supposed to make changes in this mode, that is why I disabled all the formatting buttons in this mode. If you want to make changes, such as add cloze deletions, you should first quit Markdown mode, add the deletions and toggle the Markdown button again.

**Comment by prbroadfoot** [comment]
This is what I am doing:
1) Make a card with a code block then add a cloze to it. example:
\`\`\`
SELECT * {{c1::FROM}} tablename
\`\`\`

2) Click the markdown button
3) Click the add button

I get the message "You have a cloze deletion note type but have not made any cloze deletions. Proceed?"

**Comment by Neftas** [comment]
This happens because a code block is a block of text where everything you enter is rendered literally, and is not interpreted. That's why we can enter:

    <div id="explanation">this is <em>not</em> rendered as HTML</div>

and see the actual HTML syntax, instead of the interpreted HTML. So if you enter `{{c1:whatever}}` in a code block, the same thing happens: it will display `{{c1:whatever}}` and **not** a cloze deletion.

I use this sometimes as a workaround:

```c
int main(int argc, /* code here */) {
    puts("enter teh codez");
    return 0;
}
```

and just use the answer field.

**Comment by prbroadfoot** [comment]
Ok thanks, I think it makes most sense to use the method you described with the Front/Back format and not use the Cloze format. The only other alternative I can think of is to use a rare combination of characters to surround clozes, and then have "markdown mode" convert them to clozes when formatting, but that may be more trouble than it's worth.

**Comment by Neftas** [comment]
@prbroadfoot I've added the option to enable editing of the rendered Markdown in e07768b, so if you really want, you can add cloze deletions to Markdown code blocks. You can update the add-on on [AnkiWeb](https://ankiweb.net/shared/info/162313389).
