### ISSUE TITLE
Code and cloze deletions conflict

### ISSUE THREAD

**Issue by cblupodev** [Neftas/supplementary-buttons-anki#74]
The markdown code block doesn't recognize the cloze deletion syntax. `{{c1::asdf}}` is rendered exactly like `{{c1::asdf}}` in markdown. But, it should only render `[...]` before the card is flipped

**Comment by Neftas** [comment]
This looks a lot like another issue: https://github.com/Neftas/supplementary-buttons-anki/issues/72.

**Comment by cblupodev** [comment]
Ah, right. Sorry for being lazy and not searching first. The work around is kind of a downer I Heavily use cloze deletions. It's almost the only note type I use. Putting things in front and back cards quickly becomes unmanageable for code blocks longer than two lines.

**Comment by widder** [comment]
Work around: write markdown code block, press Markdown button, strg+c copy content the rendered card, delete the card, new card and paste, add your cloze deletions

**Comment by stianlagstad** [comment]
The workaround @widder suggested works, but it would be nice to have the markdown mode working with cloze deletions.

**Comment by Neftas** [comment]
@cblupodev @widder @stianlagstad I've added the option to enable editing of the rendered Markdown in e07768b, so if you really want, you can add cloze deletions to Markdown code blocks. You can update the add-on on [AnkiWeb](https://ankiweb.net/shared/info/162313389).

**Comment by cblupodev** [comment]
Thank you Neftas

**Comment by ELLIOTTCABLE** [comment]
Hm. Could you pre-process-out cloze-deletions before passing the content to Pygments, then drop them back in exactly as they were typed? They have an extremely regular and simple syntax (notice how they break LaTeX!), so it should be pretty easy; that'd also give the user the precise behaviour they expect.

1. Input:

           :::markdown
           this *{{c1::should}}* work!

2. Post-processing:

           :::markdown
           this *_CLOZE_C0FF1E* work!

3. Pygments:

       this <span class="ge">*_CLOZE_C0FF1E*</span> work!

4. Reinstate clozes:

       this <span class="ge">*{{c1::should}}*</span> work!

ofc, not having looked too deeply into the architecture of SBA, I can't speak for sure — but I really feel it'd be worth the work!

(My particular use-case, as I feel most in the way of “code cards” violate the 20 Commandments, is mostly function descriptions/shell-script one-liners; but I'd still *love* this)

**Comment by Neftas** [comment]
@ELLIOTTCABLE If I have some time, I will look into this. (I'm also willing to take a look at pull requests.) 

Could you open a new ticket and mention this thread? Thanks.
