### ISSUE TITLE
Toggle markdown shortcut only works one way

### ISSUE THREAD

**Issue by tarzan3** [Neftas/supplementary-buttons-anki#78]
The shortcut `Ctrl + Shift + D` allows me to go from the HTML "preview" to the raw markdown input. But it doesn't go the other way (convert raw markdown back to HTML), unless I click the Toggle Markdown button. Could you please make it go both ways? Or if something prevents this from working both ways, an alternate keyboard shortcut to convert raw markdown to HTML?

**Comment by Neftas** [comment]
Hi @tarzan3, you can change the shortcuts yourself, please see the documentation.

**Comment by tarzan3** [comment]
Never mind, after disabling all supplementary buttons except Toggle Markdown, it works. (I guess one of the buttons was consuming the shortcut key going in the other direction). I was confused about having two ways of formatting (markdown and supplementary buttons), but I now see you're supposed to use one or the other to avoid loss of work. Thanks, this can be closed.
