### ISSUE TITLE
Update documentation on Anki site

### ISSUE THREAD

**Issue by tarzan3** [Neftas/supplementary-buttons-anki#82]
Great addon so far! However, it's not clear to new users that supplementary buttons and markdown should be used in a mutually exclusive way, because some formatting applied through supplementary buttons is overwritten when toggling markdown mode (example: format as a keyboard button). It's also confusing why there are two ways of formatting, until this is understood. Thanks!

**Comment by Neftas** [comment]
Yes, they are exclusive to the point that Markdown will not recognize and therefore not render anything that it doesn't know. So a keyboard shortcut will get lost, an unordered list will not. It _is_ probably a good idea to warn users about that, so thanks for the suggestion.

**Comment by tarzan3** [comment]
Sorry accidentally closed.

**Comment by Neftas** [comment]
I updated the documentation in  e07768b. It now mentions:

> ##### How the Markdown button differs from the other buttons in this add-on

> I recommend you use either Markdown or the rich formatting buttons, but not
both at the same time. Markdown was designed to be a fast and simple way to
quickly write relatively simple formatted text. As such, it won't know what to
do with complex cards that use formatting unknown to the Markdown
specification. So when clicking the Markdown button, it _will_ "erase"
formatting that it does not know how to handle. You were warned.

Do you think that will cover it? I also split the options menu for buttons and Markdown. You can update the addon from [AnkiWeb](https://ankiweb.net/shared/info/162313389).

**Comment by tarzan3** [comment]
Yeah looks good. But, believe it or not, even that may not be clear enough to less thoughtful users. How about:

> I recommend you use either Markdown language or the rich formatting buttons, but not both at the
> same time. The rich formatting buttons use a different language (HTML) to add formatting. But the
> markdown button only accepts markdown language, and will therefore remove the formatting added 
> by the rich formatting buttons. You were warned.

Thanks!
