### ISSUE TITLE
Repost a bug

### ISSUE THREAD

**Issue by Juddd** [Neftas/supplementary-buttons-anki#84]
This bug is when you click [the buttom](http://o8aucf9ny.bkt.clouddn.com/2016-07-05-04-43-31.png) to "Create a code block",which will result some content invalid.But this bug will not 100% reproduce.I have recorded [a gif](http://o8aucf9ny.bkt.clouddn.com/reportButOfPowerAddon.gif) to show it and hope can help you know it.
Note that frame of anki:

![2016-07-05-05-08-21](https://cloud.githubusercontent.com/assets/10048069/16569921/0e588390-426f-11e6-85a9-0a5c289dc30a.png)

it mean that following content have already invalid.This bug make me very upset usually,which mean I should make this card another time.

ps:The gif get dim in some frame isn't the reason result to this bug,which is a moment I'm screen-shooting in other place.

**Comment by Juddd** [comment]
The follow text for your test
```
SeedRandom[9]
point=RandomInteger[6,{6,2}]
Graphics[{Arrow[{{0,0},#}]&/@point,Blue,Arrow[{{0,0},#}]&/@IdentityMatrix[2],Red,Arrow[{{0,0},Dot[IdentityMatrix[2],#]}]&/@point}]
```
[pic1](http://o8aucf9ny.bkt.clouddn.com/2016-07-05-05-17-46.png) 
```
newPoint=Dot[Inverse[Transpose[{{1,0},{1/2,Sqrt[3]/2}}]],#]&/@point
Graphics[{Arrow[{{0,0},#}]&/@point,Blue,Arrow[{{0,0},#}]&/@{{1,0},{1/2,Sqrt[3]/2}},Red,Arrow[{{0,0},Dot[Transpose[{{1,0},{1/2,Sqrt[3]/2}}],#]}]&/@newPoint}]
```
[pic2](http://o8aucf9ny.bkt.clouddn.com/2016-07-05-05-18-36.png)

**Comment by Neftas** [comment]
@Juddd I'm sorry, but this bug report is completely unclear to me. I don't understand what the issue is.
