### ISSUE TITLE
Error when creating a fixed ordered list

### ISSUE THREAD

**Issue by aznyellojersey** [Neftas/supplementary-buttons-anki#85]
Selecting text from a card in the browser to make an ordered list. Clicking the "ordered list" option pushes the following bug:

> An error occurred in an add-on.
> Please post on the add-on forum:
> https://anki.tenderapp.com/discussions/add-ons
> 
> Traceback (most recent call last):
>   File "/Users/username/Documents/Anki/addons/extra_buttons/extra_buttons.py", line 368, in toggleOrderedList
>     OrderedList(self, self.parentWindow, utility, True)
>   File "/Users/username/Documents/Anki/addons/extra_buttons/orderedlist.py", line 36, in __init__
>     utility.preferences.prefs["fixed_ol_type"][0], 1)
> AttributeError: 'module' object has no attribute 'prefs'

**Comment by Neftas** [comment]
@aznyellojersey thanks for reporting this bug.

It has been fixed in 5dd3b2a.

You can update the addon from WebAnki. Please report if this fixes the issue for you.

**Comment by aznyellojersey** [comment]
Seems to fix the problem, thanks!
