### ISSUE TITLE
Table issue: two columns with small amount of text takes up entire screen

### ISSUE THREAD

**Issue by pchernof** [Neftas/supplementary-buttons-anki#86]
When viewing a table on the desktop anki version, if the table is only two columns with a small amount of text in each cell, you have to look across nearly half a screen of white space to read each row. There is a shitty table addon (semi broken now, randomly deletes text) called HTML table (and a spinoff called better HTML table). Both of those addons produce tables that don't use the entire screen space if it is not necessary - the tables are only as large as they need to be, no larger.

Is it possible to allow an option to make tables only as big as necessary, rather than taking up the whole screen?

Thank you very much for your wonderful addon. It is helping me in medical school bigtime.

PS: is there a way to increase the tiny font size in tables during creation? The font is fine when I use the cards, but neither the "Edit font" nor any other font affects the font size in tables during creation.

**Comment by Neftas** [comment]
Hi @pchernof thanks for the kind words. I use Anki and this addon also a lot both for study and work :)

You can change the width of the table by editing your user style sheet (_Tools_ > _Manage note types..._ > _Cards_) and adding:

```css
table {
    width: auto !important;
}
```

This will make the table adjust the size of the columns as needed, making them no larger than the biggest entry in the column. 

If you need any other visual changes to the tables, you can control them completely using CSS.

Changing the font size of the table in the same fashion by adding it to your style sheet does not work, apparently. Inline styling _does_ seem to work, however, so I will tackle this soon when I'm done with some other issues. Thanks for mentioning it!

**Comment by pchernof** [comment]
Wow, you are heroic! That is amazing, exactly what I needed.

**Comment by pchernof** [comment]
Hi, sorry to be a bother again, but your fix only helped if there is a small amount of text overall. Even with only two columns and practically nothing in the left column, the table takes up the whole screen. The right column, which contains a few sentences, can be split into multiple lines for each cell in order to make the width of the sentence small, but this has no effect on the size of the table.

![table white space](https://cloud.githubusercontent.com/assets/22597581/19073499/43c97a78-8a33-11e6-91a7-3dde1f13ddcf.jpg)

Any fix for this?

**Comment by Neftas** [comment]
Ah, yes, you also need the following:

```css
th {
    width: auto !important;
}
```

because currently they are set (inline) to be each equally wide: `(100 /  number of colums)%`.

**Comment by pchernof** [comment]
Thank you!! Looks great on my PC and phone now.

**Comment by pchernof** [comment]
Hi, how can align a small table to the center of the screen? The tables seem to always align to the left. I think I need to make a change in the style code, but I don't know how.

**Comment by Neftas** [comment]
Hi again :) you can center your table with CSS in your style sheet. If you add 

```css
table {
    width: auto !important;
    margin: 0 auto;
}
```

your table will be horizontally centered (which I think is what you want). `margin: 0 auto` means: add 0 margin to the top and bottom of the table, and adjust the right and left automatically. By the way, you won't see this change directly in your editing screen, but you will notice it when reviewing the card.

Also, you can fairly easily Google this kind of things, e.g. `css table align center` will get you enough information to tackle such problems yourself :)

**Comment by pchernof** [comment]
Thanks a lot. You are right, I will try to tackle the problem first next time.

**Comment by Neftas** [comment]
In  e07768b, I added an option to switch between using your own style sheet or use the default inline styling of the add-on. Also, the text in the table should no longer be smaller than the surrounding, non-table text when using the default inline styling.

Would you mind checking if this works correctly for you? You can update the add-on from [AnkiWeb](https://ankiweb.net/shared/info/162313389).

**Comment by pchernof** [comment]
Wow. Nicely done! The text is now a good size while editing. Also I see the option to swap between the two styles. You are such a help to so many people, I bet if you took donations you would get a few (although probably too few people using Anki for it to add up to much yet).

**Comment by Neftas** [comment]
Thanks! I am glad if I can help people be a little bit more productive :)

**Comment by kiuuik** [comment]
@Neftas: You could add a paragraph to the documentation on ankiweb about adjusting the column width. Your hint from here to use "table {width: auto !important;}" helped me a lot and made your addon even more useful but I only stumpled upon it only accidentally.

**Comment by Neftas** [comment]
Hi @kiuuik thanks for your comment. The thing is, you can style the table, just as about everything in an Anki card, to your liking by using your own style sheet. If you go to options, and select the option _Use user style sheet for styling code blocks_, you can style the table whatever way you want, not just the width.

The CSS in this thread was only meant as a workaround when that option was not yet available. If feel mentioning the fact that the user can use CSS to style their cards may be redundant, since that is one of the core options of Anki itself.
