### ISSUE TITLE
Table: top left cell resetting formatting of text

### ISSUE THREAD

**Issue by pchernof** [Neftas/supplementary-buttons-anki#89]
I typed

ASDF|ASDF|ASDF
a|A|A
sdf|ASDF|asdf

(sentences and facts and stuff)

and hit control 3, and a beautiful table was made. The top row was bolded, which I didn't need, so I unbolded all of them, with selective bolding on some areas of the top middle and top right cells. The top left cell is re-bolded whenever I edit the card and unbold it. I checked database and restarted anki to no effect.

I also copied and pasted the finished table a few times into other cards, which seemed to work fine. They all suffer from repeated bolding however, even in browser, as soon as I look at another card and then click back on the first card, re-bolded.

**Comment by Neftas** [comment]
Hi @pchernof, thanks for reporting this.

I have investigated, and it looks like this issue [originates in Anki itself](https://github.com/dae/anki/blob/master/aqt/editor.py#L881-L892).

Basically, what happens is that Anki checks the generated HTML from your card every time you edit the card, to see if the HTML is correct. It deletes certain styles from the card that probably caused some problems in the past. In this particular case, it removes the `font-weight: normal` attribute from the first `<span>` it encounters, which happens to be the upper left cell of your table. This affects how your table is displayed, as table headers are displayed in bold by QtWebKit by default.

I will probably post a bug report against Anki when I have time to do so. In the mean time, I have made a workaround, and as soon as I have posted that on AnkiWeb I will report back to you.

**Comment by Neftas** [comment]
Workaround in 9d66a46, you can update from [AnkiWeb](https://ankiweb.net/shared/info/162313389).

Can you let me know if this solves your issue?

**Comment by pchernof** [comment]
Your fixed worked wonderfully. Thank you!

**Comment by pchernof** [comment]
It's baaaaack. "Rotational force on planted foot" will always re-bold when I un-bold it.
![untitled](https://cloud.githubusercontent.com/assets/22597581/20760937/45abd9cc-b719-11e6-836f-f81d47c9aac4.jpg)

By the way, I attempted several times to adjust the padding of tables or to add vertical lines in between cells. It seems that once a table has been made, the padding or lines cannot be adjusted by modifying the style CSS. Am I going about it wrong? Is it possible to adjust padding or lines of tables that are already made?

**Comment by Neftas** [comment]
Could you post the HTML of the card here? (You can get the HTML by using <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd>. Don't just post a picture of the code; indent the code with four spaces and paste it here, so I can easily copy it, like:

    <html>
        <body>
            Body of the HTML.
        </body>
    </html>

Concerning your second question: I have obviously no idea what you have tried. If you post your CSS here, I might be able to help you.

**Comment by pchernof** [comment]
Here is a table that I made with "Style tables automatically on creation" **enabled** in the options.
![untitled](https://cloud.githubusercontent.com/assets/22597581/21063006/60f52d8a-be4b-11e6-95e0-e567ef97c822.jpg)

Here my style CSS:

.card {
 font-family: arial;
 font-size:21px;
 color: black;
 background-color: white;
 text-align: center;
  position: absolute;
  width: 100%;
  height: 100%;
  display: -webkit-box;
  -webkit-box-align: stretch;
  -webkit-box-pack: center;
  -webkit-box-orient: vertical;
}

.center{
display: inline-block;
text-align: left;
margin: auto 2.5%;
}

body {margin: 0;}

.cloze {color: blue;    #other colors: #0000ed  8800bd  purple;}

table {
  width: auto !important;
  margin: 0 auto;
}

th {width: auto !important;}

table tbody tr:nth-child(2n+1) {background-color:#f2fffd;}

.mobile .card img {max-width: auto; max-height: none;}
.mobile .card {width: 100%; height: 100%; margin: 0 auto;}
.mobile #content {margin: 0 auto;}

The same table with "Style tables automatically on creation" **disabled** in the options.
![unticked](https://cloud.githubusercontent.com/assets/22597581/21063231/6f0eda50-be4c-11e6-83c5-253ef45def94.jpg)

Please help! How do I make my tables spaced properly automatically? I tried modifying my style by adding padding in various ways - no effect on table.

**Comment by pchernof** [comment]
I found a workaround that takes very little effort. I simply indent the text in all columns after the first. Then my tables are beautifully spaced! So... problem solved.
