### ISSUE TITLE
Cannot find the "Markdown" checkbox

### ISSUE THREAD

**Issue by li-xinyang** [Neftas/supplementary-buttons-anki#90]
> Markdown is disabled by default, to keep this add-on as modularised as possible. To enable it, go to settings and tick the checkbox next to "Markdown". Restart Anki to complete the process.

I am using Anki Linux version. I'd like to enable Markdown but I cannot find setting anywhere. Any hint?

Thanks

**Comment by li-xinyang** [comment]
![screenshot from 2016-10-31 12-54-58](https://cloud.githubusercontent.com/assets/3349406/19844613/67c3c640-9f69-11e6-88b0-7dba26ef4159.png)

**Comment by Neftas** [comment]
Hi @li-xinyang I've reopened your issue, because it looks like the clarity of the documentation and menu structure leave something to be desired. I will try to make it more clear.

**Comment by Neftas** [comment]
Renamed "Button options" to just "Options" in 869fe8f5b3cefc3c156cadff2d66b8d2bc9337eb.
