### ISSUE TITLE
<code> inside links breaks Markdown formatting

### ISSUE THREAD

**Issue by badlydrawnrob** [Neftas/supplementary-buttons-anki#93]
Might be the same issue as #63 ...

> ``Only [one `primary key` per table](http://link.com)``
> Only [one `primary key` per table](http://link.com)

becomes:

<img width="573" alt="screen shot 2017-01-17 at 15 51 21" src="https://cloud.githubusercontent.com/assets/1176875/22022991/02eb0d5e-dccd-11e6-9a82-fbe9a710d7f6.png">
<img width="571" alt="screen shot 2017-01-17 at 15 51 31" src="https://cloud.githubusercontent.com/assets/1176875/22022997/0735401e-dccd-11e6-9f06-94f9e7a2422f.png">

There's a few minor issues with links, i.e `&#32;` spaces get added in the link when reverting back to Markdown (with regular text, too)

**Comment by Neftas** [comment]
Hi @badlydrawnrob, I see the problem and will investigate.

**Comment by Neftas** [comment]
@badlydrawnrob I fixed the issue in 0303b95. Would you mind checking if it indeed solves your issue?

**Comment by badlydrawnrob** [comment]
@Neftas Seems fixed to me! Good stuff 👍
