### ISSUE TITLE
Custom CSS class for <code> and <pre> in Markdown mode

### ISSUE THREAD

**Issue by deepakj86** [Neftas/supplementary-buttons-anki#94]
Firstly, thank you very much for building (and continuing to work on) this add-on; the functionality is excellent.

Secondly, this is a feature request rather than a bug. :)

At the moment, when using buttons to apply code styling, you allow a custom CSS class to be applied to the `<code>` and `<pre>` blocks. However, when using Markdown mode, the user has to manually style the code tag (or use one of the predefined language styles), and cannot use a pre-existing class. Would you please be able to add the functionality in Markdown mode as well?

I use [Code Prettify](https://github.com/google/code-prettify) to style my code, hence this request.

Thanks in advance!

**Comment by Neftas** [comment]
Hi @deepakj86 thanks for the kind words :)

When you use Markdown to style your code snippets, there is a class `codehilite` in an outer div spanning the code that is automatically added. Is this not what you are after?

With the option "Use user style sheets for styling code blocks" selected, the following code input:

    ```python
    def foo(arg):
        pass
    ```

would result in the following HTML:

```html
<div class="codehilite">
    <pre>
        <span class="k">def</span> <span class="nf">f</span><span class="p">():</span>
        <span class="k">pass</span>
    </pre>
</div>
```

But this may not be what you meant. If so, would you mind clarifying a bit? If you could be a bit more concrete (give code examples, what you see now, what you would expect), that would be perfect.

**Comment by deepakj86** [comment]
Sure, let me clarify what I meant. The way the [Code Prettify](https://github.com/google/code-prettify) script works is that it takes any text within `<pre class="prettyprint">...</pre>` or `<code class="prettyprint">...</code>`, and applies code formatting to it. It allows users to either style code elements manually, or apply pre-prepared 'themes' for the code highlighting.

My request was that for the input below:

````
```
def foo(arg):
    pass
```
````
the HTML output be as below:
```
<pre class="prettyprint">
def foo(arg):
    pass
</pre>
```

I see that at the moment, the class `codehilite` is applied to an outer `<div>` spanning the code. I had assumed (sorry, I hadn't checked the generated HTML!) that the `codehilite` class would have been applied to the `<pre>` element itself, in which case it might have been easy to give the use the option to change the default `<pre class="codehilite">` to `<pre class="whatever-user-wants">`.

This exact functionality is available when using buttons to style the code, so I had assumed it would be easy to replicate for Markdown. But I now see that the implementation for the Markdown mode is slightly different, so I don't know how simple it might be to implement this request.

**Comment by Neftas** [comment]
I see. I think the easiest way is just to type the HTML in directly in the field. So,

```html
<pre class="prettyprint">
public class Foo {
     public static void main(String... args) {
     }
}
</pre>
```

will render exactly that HTML. So, instead of typing <code>\`\`\`java\`\`\`</code>, you need to type `<pre class="prettyprint"></pre>`.

**Comment by deepakj86** [comment]
I sort of already do this, but then it makes it verbose and defeats the purpose of using Markdown... :)

Don't worry about this request if it involves changing the underlying framework... I will JS my way around it!
