### ISSUE TITLE
small typo in description of the package on anki website

### ISSUE THREAD

**Issue by abydos62** [Neftas/supplementary-buttons-anki#95]
Just wanted to let you guys know that you wrote, "Tables have the same syntax as described above for the table button." when that explanation actually occurs a bit below this statement, causing me to search what I'd already read. Cheers!

**Comment by Neftas** [comment]
@abydos62 Thanks for reporting! I can see how that's confusing. I fixed it. That's what you get when you move sections of documentation around... :)
