### ISSUE TITLE
The button of Markdown is disappear

### ISSUE THREAD

**Issue by Juddd** [Neftas/supplementary-buttons-anki#99]
I'm in latest version add-on.It's seem the button of Markdown is disappear?Look my screnshot
![](https://cloud.githubusercontent.com/assets/10048069/24632260/181a92f2-18f6-11e7-8e23-b8063b103a35.png)

**Comment by Neftas** [comment]
Hi @Juddd, you have to enable the Markdown button from the settings. Please have a look at the documentation (or just go to _Tools_ > _Power Format Pack add-on (options)_ > _Options..._ > _Markdown_ > _Enable Markdown_).

**Comment by Juddd** [comment]
@Neftas Thanks for your response.

**Comment by Juddd** [comment]
@Neftas Thanks for your response in time,the *Markdown* is very convenient to me.But it seem the shortcut ctrl+shift+0 doesn't work,I have to click that *Markdown button*.Could you help to fix it?and I can provide any *.log* file to you if necessity.

**Comment by Neftas** [comment]
You can manually [change the keybindings](https://github.com/Neftas/supplementary-buttons-anki#custom-user-defined-keybindings) to something that works for you.
